### PR TITLE
Support for arguments passed as query string parameters

### PR DESCRIPTION
**Pull request by adunkman**
I added support for arguments in the URL, for example: 

/1/boards/{board}/cards?filter=all

### CODE REVIEW

**Comment by lmatteis** [comment]
Hey, I got your tweet as well. I don't have time to maintain and review the commits for this project. Would you like to take over? Maybe I can give you access to the npm repo for this, if it's possible.

**Comment by adunkman** [comment]
Sure, I can maintain it. I do ask though that if I'm taking over the NPM repository that we transfer the git repository from your github user to mine, so all the pull requests and issues are logged for me to deal with instead of you. 

According to http://help.github.com/move-a-repo/ you'll have to contact support (https://github.com/contact) to move a repo from a user to a user.

My email address on NPM packages is andrew@dunkman.org

**Comment by adunkman** [comment]
By the way, the command to add an owner to NPM (I believe):

npm owner add andrew@dunkman.org node-trello

**Comment by lmatteis** [comment]
weird i get: 

```
npm ERR! Error getting user data for andrew@dunkman.org
npm ERR! Error: not_found missing: -/user/org.couchdb.user:andrew@dunkman.org
```

you sure it's your npm user?

**Comment by adunkman** [comment]
Erp, try "adunkman" instead. 

adunkman &lt;andrew@dunkman.org&gt; is what it lists for me.

**Comment by lmatteis** [comment]
yep that worked :)

**Pull request closed without merging**
